### PR TITLE
updated the perforce server to 2018.2

### PR DESCRIPTION
**Pull request by iwanzarembo**
Your base image was great, but the perforce server was a bit outdated.
So I updated the version and adjusted the scripts to be able to run them with the new version.

I hope you are ok with the changes.

### CODE REVIEW

**Comment by noonien** [comment]
Thanks for the contributions!

I'd be happy to merge the changes, could you clean the commits up a bit?

Also, remove the .editorconfig file, I don't feel this is needed.

Cheers

**Comment by iwanzarembo** [comment]
You would like to squash the commits? 
about the .editorconfig. It is a IDE independent configuration file. See https://editorconfig.org/
I can remove it of course.

p.s. Sorry for the late response.

**Comment by noonien** [comment]
Yes, a squash would be great.

While i know editorconfig can be used by many IDEs, this project is not big enough to warrant one.

**Comment by iwanzarembo** [comment]
I squashed the commits into one and deleted the etirodconfig file.

**Comment by noonien** [comment]
Thanks for your contribution!

There appears to be some typos in your commit message. Can you please fix them?

Will gladly merge afterwards, everything else seems ok!

**Comment by iwanzarembo** [comment]
updated the commit message and removed the typos.

**Comment by noonien** [comment]
Great, thank you!

**Pull request merged**
